### PR TITLE
Read data not dump

### PR DESCRIPTION
**Pull request by Leimeroth**
Ugly fix for #57

### CODE REVIEW

**Comment by Leimeroth** [comment]
This works without throwing errors now. I am not sure if
```
def remap_box(lmp, x, y, z):
    lmp.command("run 0")
    lmp.command("change_box     all x final 0.0 %f y final 0.0 %f z final 0.0 %f remap units box"%(x, y, z))
    return lmp
```
works as intended with non orthogonal boxes, but I am also confused why it is necessary at all?
Comments in the code state:
```
#remap the box to get the correct pressure
```
But I don't think lammps gives the wrong pressure for boxes with a origin different from (0, 0, 0), since that would mess with basically every npt calculation from everyone.

**Comment by Leimeroth** [comment]
Updated with another workaround. For one of my structures pyscal kept refusing to find neighbors with an adaptive cutoff for some reason, so I just wrapped it into a try except block and use a fixed 5.0 angstrom cutoff when adaptive does not work.
Maybe would be good to add it to the convergence parameters instead of hard coding it ?

**Comment by Leimeroth** [comment]
Also locally the tests seem to run fine, and the error seems unrelated to my changes so I am confused why it failed.

**Comment by Leimeroth** [comment]
Seems like failing tests were due to the example input file changes which somehow slipped in.
Could you merge this @srmnitc ?

**Comment by srmnitc** [comment]
@Leimeroth looks good to me! I still would like to look a bit more in detail. I will probably merge tomorrow. Thanks for the contribution!

**Pull request merged**
